version: '2'
services:
    betagateway-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/betaGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=betaGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
